server:
  port:80

#指定配置文件dev
spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:top/arhi/mapper/*Mapper.xml
  type-aliases-package: top.arhi.domain
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #map-underscore-to-camel-case: false
