elasticsearch:
  hostname: 127.0.0.1
  port: 9200
  schema: http
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: top.arhi.domain