# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_ajax?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  dubbo:
    application:
      name: springboot-dubbo-provider #应用名
    registry:
      address: zookeeper://192.168.31.135 #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20880 #dubbo服务暴露的端口
    scan: top.arhi.service.impl #扫描的包名
  aop:
    proxy-target-class: true #

server:
  port: 8080 #Tomcat端口

mybatis-plus:
  global-config:
    db-config:
      # id 自增
      id-type: auto
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: top.arhi.domain
  mapper-locations: cn/fiesacyum/dao/*Dao.xml
