server:
  port: 80
spring:
  application:
    name: eureka-gateway-server
  cloud:
    gateway:
      #路由配置,转发规则
      routes: #集合
      #id 唯一标识,默认为一个uuid
      #uri:转发路径
      #predicates:调教用于请求网关路径的匹配规则
        #可以配置多个route路由
      - id: eureka-client-provider
        uri: lb://EUREKA-CLIENT-PROVIDER #微服务应用名称 pom文件需要引入eureka-client并在启动类上开启注解@EnableEurekaClient才能解析
        #静态路由
        #uri: http://localhost:8001/
        predicates:
        - Path=/system/goods/**
        #配置过滤器
        filters:
        - StripPrefix=1 #将/system/goods/** 减去/system或拼接到动态路由上.当在发起请求时,仍需以该路径发起请求.
      discovery:
        locator:
          enabled: true #设置为true 请求路径添加与不添加为微服务名称都可映射到目标地址
          lower-case-service-id: true # 允许为小写
#作用:通过route路径到后台管理系统,或者手机等客户端.
# localhsot:80/system/goods/findOne/1
# localhost:eureka-client-provider/goods/findOne/1
