server:
  port: 80
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    port: 6379
    host: 127.0.0.1

leetcode:
  sms:
    url: http://106.ihuyi.com/webservice/sms.php?method=Submit
    account: C80305290
    password: e6e474c1e7b4f88889f3fd67b474bd68